# Database Credentials and Information
db_name: "neo4j"
uri: "bolt://localhost:7687"
user: "neo4j"
password: "12345678"
import_directory: "C:/Users/s156229/.Neo4jDesktop/relate-data/dbmss/dbms-f239c3b8-6596-4b15-82eb-1ab321ac0aa0/import"

# Dataset information
dataset_name: "BPIC14"
semantic_header_path: "json_files/BPIC14.json"
dataset_description_path: "json_files/BPIC14_DS.json"
use_sample: true

# Import settings
verbose: false
batch_size: 10000
use_preprocessed_files: false
